# 애플리케이션 이름 설정
spring:
  application:
    name: fcm-demo

  # H2 데이터베이스 설정
  datasource:
    url: jdbc:h2:mem:fcmdb # H2 인메모리 데이터베이스 URL
    username: sa # H2 데이터베이스 사용자 이름
    password:  # H2 데이터베이스 비밀번호
    driver-class-name: org.h2.Driver # H2 데이터베이스 드라이버 클래스

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update # 애플리케이션 실행 시 자동으로 테이블 생성
    show-sql: true # SQL 쿼리 로그 출력
    properties:
      hibernate:
        format_sql: true # 로그 출력 시 SQL 쿼리 포맷팅

  # H2 콘솔 설정
  h2:
    console:
      enabled: true # H2 콘솔 사용 가능
      path: /h2-console # H2 콘솔 접근 경로

  # 정적 리소스 설정
  web:
    resources:
      static-locations: classpath:/static/ # 정적 리소스 경로
      cache:
        period: 0 # 캐싱 기간 0초 (개발 환경에서는 캐싱 비활성화)

# 서버 설정
server:
  port: 8080 # 서버 포트
  servlet:
    context-path: / # 컨텍스트 경로
  compression:
    enabled: true # HTTP 응답 압축 활성화
  http2:
    enabled: true # HTTP/2 지원 활성화

# Firebase 서비스 계정 파일 경로
firebase:
  service-account-file: classpath:firebase-service-account.json

# Swagger 설정
springdoc:
  api-docs:
    path: /api-docs # API 문서 경로
  swagger-ui:
    path: /swagger-ui.html # Swagger UI 경로
