spring:
  application:
    name: fcm-demo

  # H2 ?????? ??
  datasource:
    url: jdbc:h2:mem:fcmdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # JPA ??
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # H2 ?? ???
  h2:
    console:
      enabled: true
      path: /h2-console

  # ?? ??? ??
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 0

# ?? ??
server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true
  http2:
    enabled: true

# Firebase ??
firebase:
  service-account-file: classpath:firebase-service-account.json

# Swagger ??
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
